security:
    role_hierarchy:
        ROLE_ADMIN:  [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MANAGER: ROLE_CONSULTANT
        ROLE_CONSULTANT: ROLE_USER

    providers:
        main:
          entity: { class: ConsultBusinessBundle:User, property: username }

    encoders:
        Consult\Bundle\BusinessBundle\Entity\User:
          algorithm:   md5
          iterations: 1
          encode_as_base64: false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /
            logout:
                path:   /logout
                target: /
            switch_user: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
