parameters:

services:
     consult.listener.login:
         class: Consult\Bundle\FrontendBundle\Listener\UserLogin
         arguments: [ @doctrine, @service_container ]
         tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }